name: Rust CI

on:
  push:
    branches: master
  pull_request:
    branches: master

env:
  # Not needed in CI, should make things a bit faster
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  # Build smaller artifacts to avoid running out of space in CI
  RUSTFLAGS: -C strip=debuginfo

jobs:
  ruct_ci:
    name: Rust CI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          profile: minimal
          components: rustfmt,clippy
          override: true

      - name: Cache
        uses: Swatinem/rust-cache@v2
      
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release
      
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all -- -D warnings
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release